import torch.nn.functional as F
import cv2
cv2.setNumThreads(0)
import gc
import re
import os
import torch

import time
import sys
import requests
import random
import heapq
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

import torchvision.transforms as transforms
from scipy.interpolate import interp1d
from scipy.ndimage import center_of_mass
from skimage.segmentation import slic, mark_boundaries
from sklearn.metrics import auc
from decord import VideoReader, cpu
from PIL import Image
from textwrap import fill
import torch.utils.checkpoint as checkpoint
from io import BytesIO
from itertools import combinations

from qwen_vl_utils import process_vision_info

from . import io_utils
from . import model_utils
from . import cv_utils

import concurrent.futures

DEFAULT_VIDEO_TOKEN = "<video>"


def eprint(*args, **kwargs):
    """Helper to log to stderr."""
    sep = ' '
    combined_text = sep.join(str(arg) for arg in args)
    wrapped_lines = []
    for line in combined_text.splitlines():
        if line.strip() == "":
            wrapped_lines.append("")
        else:
            wrapped_lines.append(fill(line, width=80))
    final_text = "\n".join(wrapped_lines)
    print(final_text, file=sys.stderr, **kwargs)

def save_igos_heatmaps(video_array, mask_numpy, outdir, prefix, alpha=0.5):
    """
    Saves heatmaps and overlays for the continuous masks generated by iGOS.
    video_array: (T, H, W, C) numpy array of original frames (0-255)
    mask_numpy: (H, W) numpy array of the upscaled iGOS mask
    """
    os.makedirs(outdir, exist_ok=True)
    
    # Normalize the mask to 0-1 for the colormap
    mask_min, mask_max = mask_numpy.min(), mask_numpy.max()
    if mask_max - mask_min > 0:
        norm_mask = (mask_numpy - mask_min) / (mask_max - mask_min)
    else:
        norm_mask = mask_numpy

    # Create the heatmap (0-1 float32 scale)
    heatmap_uint8 = np.uint8(255 * norm_mask)
    heatmap = cv2.applyColorMap(heatmap_uint8, cv2.COLORMAP_JET)
    heatmap = cv2.cvtColor(heatmap, cv2.COLOR_BGR2RGB).astype(np.float32) / 255.0

    visualized_frames = []

    # Apply the heatmap to every frame in the video array
    for i, frame in enumerate(video_array):
        image_float = frame.astype(np.float32) / 255.0
        
        # Overlay: 50% heatmap + 50% image (matching your provided code)
        overlay = alpha * heatmap + (1.0 - alpha) * image_float
        overlay = np.clip(overlay, 0.0, 1.0)
        
        # Save individual frames (optional, but matches your original request)
        plt.imsave(os.path.join(outdir, f'{prefix}_frame{i}_heatmap.jpg'), heatmap)
        plt.imsave(os.path.join(outdir, f'{prefix}_frame{i}_overlay.jpg'), overlay)
        
        # Accumulate frames for a GIF
        overlay_uint8 = np.uint8(255 * overlay)
        visualized_frames.append(Image.fromarray(overlay_uint8))

    # Save as GIF for consistency with your other methods
    if visualized_frames:
        visualized_frames[0].save(
            os.path.join(outdir, f'{prefix}_overlay.gif'),
            save_all=True,
            append_images=visualized_frames[1:],
            duration=250,
            loop=0
        )

def visualize_spix(video_array, baseline_array, tubelets, selected_tubes, output_path):
    masked_frames = cv_utils.apply_universal_mask(video_array, baseline_array, tubelets, selected_tubes)
    masked_frames[0].save(
        output_path, save_all=True, append_images=masked_frames[1:], duration=250, loop=0
    )

def visualize_frames(frames, output_path):
    frames[0].save(
        output_path, save_all=True, append_images=frames[1:], duration=250, loop=0
    )

def visualize_tubelets(video_array, tubelet_labels, output_path):
    visualized_video = []
    for i in range(len(video_array)):
        frame = video_array[i]
        label_slice = tubelet_labels[i]
        boundary_img = mark_boundaries(frame, label_slice)
        boundary_img_uint8 = (boundary_img * 255).astype(np.uint8)
        visualized_video.append(Image.fromarray(boundary_img_uint8))
    visualized_video[0].save(
        output_path, save_all=True, append_images=visualized_video[1:], duration=250, loop=0 
    )
    print(f"Saved visualization to {output_path}")


def visualize_interaction_matrix(interaction_matrix, output_path):
    plt.figure(figsize=(10, 8))
    max_val = np.max(np.abs(interaction_matrix))
    if max_val == 0:
        max_val = 1.0 
    sns.heatmap(
        interaction_matrix, cmap="RdYlGn", center=0, vmin=-max_val, vmax=max_val,
        annot=True, fmt=".3f", linewidths=.5,
        cbar_kws={'label': 'Interaction Index (Red=Redundant (lim -2), Green=Synergistic (lim 2))'}
    )
    plt.title("Frame Pairwise Interactions (Shapley)")
    plt.xlabel("Frame Index J")
    plt.ylabel("Frame Index I")
    plt.tight_layout()
    plt.savefig(output_path, dpi=300)
    plt.close()


def visualize_heatmap(video_array, tubelet_labels, tubelet_scores, output_path, alpha=0.7, blur_fraction=0.15, gamma=1.0):
    visualized_video = []
    max_id = tubelet_labels.max()
    score_map = np.zeros(max_id + 1, dtype=np.float32)
    
    # Clip negative scores to 0 (we only care about positive signal)
    for tid, score in tubelet_scores.items():
        score_map[tid] = max(0.0, score)
        
    # Normalize the scores so the maximum value is exactly 1.0
    mask_max = score_map.max()
    if mask_max > 0:
        score_map = score_map / mask_max
        
    # Optional: Apply gamma to boost mid-tones if needed
    #score_map = np.power(score_map, gamma)
    heatmap_mask = score_map[tubelet_labels]
    H, W = video_array[0].shape[:2]
    k_size = int(min(H, W) * blur_fraction)
    k_size = k_size + 1 if k_size % 2 == 0 else k_size 
    k_size = max(15, k_size) 

    for i in range(len(video_array)):
        image = video_array[i].astype(np.float32) # Ensure float for smooth blending
        mask_frame = heatmap_mask[i]
        # Blur the 0-1 mask
        blurred_mask = cv2.GaussianBlur(mask_frame, (k_size, k_size), 0)
        # Convert to 0-255 for the colormap
        heatmap_uint8 = np.uint8(255 * blurred_mask)
        heatmap = cv2.applyColorMap(heatmap_uint8, cv2.COLORMAP_JET )
        heatmap = cv2.cvtColor(heatmap, cv2.COLOR_BGR2RGB).astype(np.float32)
        # We scale the alpha by the blurred mask itself.
        # Where the mask is 0, dynamic_alpha is 0 (100% original image).
        # Where the mask is 1, dynamic_alpha is `alpha` (e.g., 60% heatmap, 40% image).
        dynamic_alpha = blurred_mask[..., np.newaxis] * alpha
        overlay = (1.0 - dynamic_alpha) * image + dynamic_alpha * heatmap
        overlay = np.clip(overlay, 0, 255).astype(np.uint8)
        visualized_video.append(Image.fromarray(overlay))
        
    visualized_video[0].save(
        output_path, save_all=True, append_images=visualized_video[1:], duration=250, loop=0
    )
    print(f"Saved heatmap visualization to {output_path}")

def visualize_gradients(gradients, frames, tubelets, save_folder, step, title="IG_Step", alpha=0.6, blur_fraction=0.08):
    """
    Overlays tubelet gradients onto original frames using cv2/PIL for fast GIF generation.
    Blue = Negative (suppresses output), Red = Positive (supports output).
    Unimportant areas (zero gradient) remain the original grayscale frame.
    """
    #-- Map 1D tubelet gradients back to the 3D video space (T, H, W)
    if torch.is_tensor(gradients):
        gradients = gradients.detach().cpu().numpy()
    if torch.is_tensor(tubelets):
        tubelets = tubelets.detach().cpu().numpy()
        
    spatial_grads = gradients[tubelets].astype(np.float32)
    T, H, W = spatial_grads.shape
    
    #-- Determine symmetric limits for the diverging colormap
    vmax = np.max(np.abs(spatial_grads))
    if vmax == 0: vmax = 1e-9 # Prevent division by zero
    
    #-- Dynamic blur kernel size based on frame resolution
    k_size = int(min(H, W) * blur_fraction)
    k_size = k_size + 1 if k_size % 2 == 0 else k_size 
    k_size = max(5, k_size) 

    visualized_video = []
    cmap = plt.get_cmap('coolwarm') # Still the easiest way to get Blue-White-Red

    for t in range(T):
        #-- Extract and format the base image
        image = frames[t]
        if torch.is_tensor(image):
            image = image.detach().cpu().numpy()
            if image.ndim == 3 and image.shape[0] == 3: # If channels first (C, H, W)
                image = np.transpose(image, (1, 2, 0))
        else:
            # ---> FIX: Convert PIL Image (or other types) to NumPy array <---
            image = np.array(image)
                
        # Ensure image is in 0-255 float range for blending
        if image.max() <= 1.0:
            image = image * 255.0
        image = image.astype(np.float32)
        
        #-- Convert base image to 3-channel grayscale so the Red/Blue heatmap pops
        # Check if grayscale already (shape (H, W)) to prevent index errors
        if image.ndim == 2:
            image = image[..., np.newaxis]
            
        gray_image = np.mean(image, axis=-1, keepdims=True)
        gray_image = np.repeat(gray_image, 3, axis=-1)
        
        #-- Process the gradient mask
        grad_frame = spatial_grads[t]
        
        # Blur the raw gradients to smooth the blocky tubelets
        blurred_grad = cv2.GaussianBlur(grad_frame, (k_size, k_size), 0)
        
        # Calculate absolute magnitude for the alpha mask (0.0 to 1.0)
        magnitude = np.abs(blurred_grad) / vmax
        magnitude = np.clip(magnitude, 0, 1)
        
        # Normalize gradients to [0, 1] for the colormap (-vmax -> 0.0, 0 -> 0.5, +vmax -> 1.0)
        norm_grad = (blurred_grad / vmax + 1.0) / 2.0
        norm_grad = np.clip(norm_grad, 0, 1)
        
        # Apply colormap to get RGB overlay (drop the alpha channel from cmap)
        heatmap_rgba = cmap(norm_grad)
        heatmap_rgb = (heatmap_rgba[..., :3] * 255.0).astype(np.float32)
        
        #-- Perform dynamic alpha blending
        # Where magnitude is 0, alpha is 0 (100% original frame)
        # Where magnitude is 1, alpha is `alpha` (e.g., 60% heatmap, 40% frame)
        dynamic_alpha = magnitude[..., np.newaxis] * alpha
        overlay = (1.0 - dynamic_alpha) * gray_image + dynamic_alpha * heatmap_rgb
        
        overlay = np.clip(overlay, 0, 255).astype(np.uint8)
        visualized_video.append(Image.fromarray(overlay))

    # --- SAVE AS GIF ---
    os.makedirs(save_folder, exist_ok=True)
    save_path = os.path.join(save_folder, f"{title}_step_{step:03d}.gif")
    
    visualized_video[0].save(
        save_path, 
        save_all=True, 
        append_images=visualized_video[1:], 
        duration=250, # 4 FPS 
        loop=0
    )

def evaluate_confidence(model, processor, frames, input_ids, output_ids, is_qwen):
    """
    Evaluates the model's probability for the target output_ids.
    Returns the decoded prediction and the probability score.
    """
    with torch.no_grad():
        if is_qwen:
            inputs = processor(text=[" "], videos=[frames], padding=True, return_tensors="pt", max_pixels=112896).to(model.device)
            forward_kwargs = {
                "input_ids": torch.cat((input_ids, output_ids), dim=1),
                "attention_mask": torch.ones_like(torch.cat((input_ids, output_ids), dim=1)).to(model.device),
                "pixel_values_videos": inputs['pixel_values_videos'].to(dtype=model.dtype),
                "video_grid_thw": inputs['video_grid_thw'],
                "use_cache": False
            }
        else:
            inputs = processor(text=" ", videos=frames, return_tensors="pt").to(model.device)
            forward_kwargs = {
                "input_ids": torch.cat((input_ids, output_ids), dim=1),
                "attention_mask": torch.ones_like(torch.cat((input_ids, output_ids), dim=1)).to(model.device),
                "pixel_values_videos": inputs['pixel_values_videos'].to(dtype=model.dtype),
                "use_cache": False
            }
        outputs = model(**forward_kwargs)
        logits = outputs.logits
        out_len = output_ids.shape[-1]
        target_logits = logits[:, -out_len - 1 : -1, :]
        predicted_ids = torch.argmax(target_logits[:, 0:1, :], dim=-1) #Mmhhh.. what is this?
        probs = F.softmax(target_logits, dim=-1)
        target_probs = probs.gather(dim=-1, index=output_ids.unsqueeze(-1)).squeeze(-1)
        mean_prob = target_probs.mean().item()
        entropy = -torch.sum(probs * torch.log(probs + 1e-7), dim=-1)
        mean_entropy = entropy.mean().item()
    return predicted_ids, mean_prob, mean_entropy


def plot_and_save_auc(percentages, ins_curve, del_curve, auc_ins, auc_del, prob_orig, prob_blur, output_dir, ivd):
    """Handles matplotlib generation and disk I/O."""
    plt.figure(figsize=(8, 6))
    plt.plot(percentages, ins_curve, label=f'Insertion (AUC={auc_ins:.3f})', color='green', marker='o')
    plt.plot(percentages, del_curve, label=f'Deletion (AUC={auc_del:.3f})', color='red', marker='x')
    plt.axhline(y=prob_orig, color='gray', linestyle='--', label='Original Prob')
    plt.axhline(y=prob_blur, color='blue', linestyle='--', label='Blurred Prob')
    
    plt.title("Insertion / Deletion Curves")
    plt.xlabel("Fraction of Total Video Pixels Revealed/Masked")
    plt.ylabel("Target Probability")
    plt.legend()
    plt.grid(True)
    
    os.makedirs(output_dir, exist_ok=True)
    plt.savefig(os.path.join(output_dir, f"{ivd}_auc_curves.png"))
    plt.close()

def evaluate_auc(args, model, processor, full_ids, output_ids, frames, video_array, tubelets, selected_tubes, baseline_ins_arr, baseline_del_arr, ivd=0, positions=None, num_steps=20):
    eprint("\n--- Starting Clean AUC Evaluation ---")
    T, H, W, _ = video_array.shape
    
    baseline_ins_frames = [Image.fromarray(f.astype(np.uint8)) for f in baseline_ins_arr]
    baseline_del_frames = [Image.fromarray(f.astype(np.uint8)) for f in baseline_del_arr]
    
    prob_orig = model_utils.get_prob(args, model, processor, full_ids, output_ids, frames, positions)
    prob_blur = model_utils.get_prob(args, model, processor, full_ids, output_ids, baseline_ins_frames, positions)
    prob_del_base = model_utils.get_prob(args, model, processor, full_ids, output_ids, baseline_del_frames, positions)
    
    # Rank the pixels (Higher value = More Important)
    pixel_ranks = np.zeros((T, H, W), dtype=np.float32)
    num_selected = len(selected_tubes)
    
    for i, t_id in enumerate(selected_tubes):
        pixel_ranks[tubelets == t_id] = num_selected - i
        
    # Add tiny uniform noise to strictly break ties across non-selected background pixels
    np.random.seed(getattr(args, 'manual_seed', 42))
    pixel_ranks += np.random.rand(*pixel_ranks.shape) * 0.5 
    
    # Main Evaluation Loop
    fractions = np.linspace(0.0, 1.0, num_steps + 1)
    ins_curve_raw, del_curve_raw = [], []
    
    for f in fractions:
        # Find the threshold that isolates the top `f` fraction of pixels
        # If f=0 -> thresh = max (mask is entirely False)
        # If f=1 -> thresh = min (mask is entirely True)
        thresh = np.percentile(pixel_ranks, 100.0 * (1.0 - f))
        mask = pixel_ranks >= thresh
        mask_expanded = mask[..., np.newaxis]
        
        # -- Deletion --
        # f=0: Original video. f=1: Baseline masked video.
        del_array = np.where(mask_expanded, baseline_del_arr, video_array).astype(np.uint8)
        frames_del = [Image.fromarray(frm) for frm in del_array]
        p_del = model_utils.get_prob(args, model, processor, full_ids, output_ids, frames_del, positions)
        del_curve_raw.append(p_del)

        # -- Insertion --
        # f=0: Baseline blurred video. f=1: Original video.
        ins_array = np.where(mask_expanded, video_array, baseline_ins_arr).astype(np.uint8)
        frames_ins = [Image.fromarray(frm) for frm in ins_array]
        p_ins = model_utils.get_prob(args, model, processor, full_ids, output_ids, frames_ins, positions)
        ins_curve_raw.append(p_ins)

    # Standard XAI Metric Normalization (Clamped to prevent > 1.0 anomalies)
    norm_ins = np.clip((np.array(ins_curve_raw) - prob_blur) / (prob_orig - prob_blur + 1e-7), 0, 1)
    norm_del = np.clip((np.array(del_curve_raw) - prob_del_base) / (prob_orig - prob_del_base + 1e-7), 0, 1)

    auc_ins = auc(fractions, norm_ins)
    auc_del = auc(fractions, norm_del)

    eprint(f"Final AUC - Insertion: {auc_ins:.4f} | Deletion: {auc_del:.4f}")

    # Plot raw probabilities for readability
    plot_and_save_auc(list(fractions), ins_curve_raw, del_curve_raw, auc_ins, auc_del, prob_orig, prob_blur, args.output_dir, ivd)
    
    return auc_ins, auc_del

# -- For iGOS++


def evaluate_auc_pixel(args, model, processor, full_ids, output_ids, frames, continuous_mask, ivd=0, positions=None):
    eprint("\n--- Starting iGOS AUC Evaluation (Reference Match) ---")
    video_array = np.stack([np.array(img) for img in frames])
    T, H, W, C = video_array.shape
    num_pixels = T * H * W
    
    step = max(1, num_pixels // 50)
    
    baseline_ins = cv_utils.get_baseline_insertion(args, video_array)
    baseline_del = cv_utils.get_baseline_deletion(args, video_array)
    
    prob_orig = model_utils.get_prob(args, model, processor, full_ids, output_ids, frames, positions)
    frames_blur = [Image.fromarray(f) for f in baseline_ins]
    prob_blur = model_utils.get_prob(args, model, processor, full_ids, output_ids, frames_blur, positions)
    
    # Curves track raw probabilities for the plotting function
    del_curve = [prob_orig]
    ins_curve = [prob_blur]
    index = [0.0]
    
    # Broadcast and sort pixels
    pixel_ranks = np.tile(continuous_mask, (T, 1, 1))
    np.random.seed(args.manual_seed)
    pixel_ranks += np.random.rand(*pixel_ranks.shape) * 1e-5
    sorted_ranks = np.sort(pixel_ranks, axis=None)[::-1] 

    for pixels in range(0, num_pixels, step):
        # Calculate exactly how many pixels are evaluated in this step
        current_step_size = step if pixels + step < num_pixels else num_pixels - pixels
        
        idx = min(pixels + current_step_size - 1, num_pixels - 1)
        thresh = sorted_ranks[idx]
        
        current_mask = pixel_ranks >= thresh
        mask_expanded = current_mask[..., np.newaxis] 
        
        # --- Deletion ---
        del_array = np.where(mask_expanded, baseline_del, video_array).astype(np.uint8)
        frames_del = [Image.fromarray(f) for f in del_array]
        p_del = model_utils.get_prob(args, model, processor, full_ids, output_ids, frames_del, positions)
        del_curve.append(p_del) 
        
        # --- Insertion ---
        ins_array = np.where(mask_expanded, video_array, baseline_ins).astype(np.uint8)
        frames_ins = [Image.fromarray(f) for f in ins_array]
        p_ins = model_utils.get_prob(args, model, processor, full_ids, output_ids, frames_ins, positions)
        ins_curve.append(p_ins) 
        
        index.append((pixels + current_step_size) / num_pixels)

    # --- NEW: Normalize curves before AUC calculation (Matching evaluate_auc) ---
    norm_ins_curve = [(p - prob_blur) / (prob_orig - prob_blur + 1e-7) for p in ins_curve]
    norm_del_curve = [(p - prob_blur) / (prob_orig - prob_blur + 1e-7) for p in del_curve]

    # Compute Normalized AUC using sklearn
    auc_del = auc(index, norm_del_curve)
    auc_ins = auc(index, norm_ins_curve)

    eprint(f"Final Normalized AUC - Insertion: {auc_ins:.4f} | Deletion: {auc_del:.4f}")
    
    # Generate the visual curves using the unified plotting function
    plot_and_save_auc(
        percentages=index, 
        ins_curve=ins_curve, 
        del_curve=del_curve, 
        auc_ins=auc_ins, 
        auc_del=auc_del, 
        prob_orig=prob_orig, 
        prob_blur=prob_blur, 
        output_dir=args.output_dir, 
        ivd=ivd
    )
    
    return auc_ins, auc_del